# Generated by Django 3.2.6 on 2021-09-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_alter_photomodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='gall'),
        ),
    ]
